static var cards = [
	# "Shockwave",
	"Spincellerate", 
	"Spincellerate", 
	"Reinforce", 
	"Reinforce", 
	"Scaleballs", 
	"Scaleballs", 
	"Scaleballs", 
	"Scaleballs", 
	"Multchance", 
	"Multchance", 
	"Multchance", 
	"Multchance", 
	"Multchance", 
	"Multchance", 
	"Plonky", 
	]
